// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_cache.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldPresence = `-- name: CleanupOldPresence :exec
DELETE FROM user_presence
WHERE last_ping < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) CleanupOldPresence(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldPresence)
	return err
}

const deleteAICacheByKey = `-- name: DeleteAICacheByKey :exec
DELETE FROM ai_cache
WHERE user_id = $1 AND cache_type = $2 AND cache_key = $3
`

type DeleteAICacheByKeyParams struct {
	UserID    int32
	CacheType string
	CacheKey  string
}

func (q *Queries) DeleteAICacheByKey(ctx context.Context, arg DeleteAICacheByKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAICacheByKey, arg.UserID, arg.CacheType, arg.CacheKey)
	return err
}

const deleteAICacheByType = `-- name: DeleteAICacheByType :exec
DELETE FROM ai_cache
WHERE user_id = $1 AND cache_type = $2
`

type DeleteAICacheByTypeParams struct {
	UserID    int32
	CacheType string
}

func (q *Queries) DeleteAICacheByType(ctx context.Context, arg DeleteAICacheByTypeParams) error {
	_, err := q.db.Exec(ctx, deleteAICacheByType, arg.UserID, arg.CacheType)
	return err
}

const deleteAllAICache = `-- name: DeleteAllAICache :exec
DELETE FROM ai_cache
WHERE user_id = $1
`

func (q *Queries) DeleteAllAICache(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteAllAICache, userID)
	return err
}

const deleteExpiredAICache = `-- name: DeleteExpiredAICache :exec
DELETE FROM ai_cache
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredAICache(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAICache)
	return err
}

const getAICache = `-- name: GetAICache :one
SELECT id, user_id, cache_type, cache_key, prompt_hash, data_hash, response, created_at, expires_at, listen_count FROM ai_cache
WHERE user_id = $1 AND cache_type = $2 AND cache_key = $3
`

type GetAICacheParams struct {
	UserID    int32
	CacheType string
	CacheKey  string
}

func (q *Queries) GetAICache(ctx context.Context, arg GetAICacheParams) (AiCache, error) {
	row := q.db.QueryRow(ctx, getAICache, arg.UserID, arg.CacheType, arg.CacheKey)
	var i AiCache
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CacheType,
		&i.CacheKey,
		&i.PromptHash,
		&i.DataHash,
		&i.Response,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ListenCount,
	)
	return i, err
}

const getUserPresence = `-- name: GetUserPresence :one
SELECT user_id, last_ping FROM user_presence
WHERE user_id = $1
`

func (q *Queries) GetUserPresence(ctx context.Context, userID int32) (UserPresence, error) {
	row := q.db.QueryRow(ctx, getUserPresence, userID)
	var i UserPresence
	err := row.Scan(&i.UserID, &i.LastPing)
	return i, err
}

const isUserOnline = `-- name: IsUserOnline :one
SELECT EXISTS(
    SELECT 1 FROM user_presence
    WHERE user_id = $1 AND last_ping > NOW() - INTERVAL '30 seconds'
) AS online
`

func (q *Queries) IsUserOnline(ctx context.Context, userID int32) (bool, error) {
	row := q.db.QueryRow(ctx, isUserOnline, userID)
	var online bool
	err := row.Scan(&online)
	return online, err
}

const upsertAICache = `-- name: UpsertAICache :exec
INSERT INTO ai_cache (user_id, cache_type, cache_key, prompt_hash, data_hash, response, expires_at, listen_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, cache_type, cache_key)
DO UPDATE SET
    prompt_hash = EXCLUDED.prompt_hash,
    data_hash = EXCLUDED.data_hash,
    response = EXCLUDED.response,
    created_at = NOW(),
    expires_at = EXCLUDED.expires_at,
    listen_count = EXCLUDED.listen_count
`

type UpsertAICacheParams struct {
	UserID      int32
	CacheType   string
	CacheKey    string
	PromptHash  string
	DataHash    string
	Response    string
	ExpiresAt   time.Time
	ListenCount pgtype.Int4
}

func (q *Queries) UpsertAICache(ctx context.Context, arg UpsertAICacheParams) error {
	_, err := q.db.Exec(ctx, upsertAICache,
		arg.UserID,
		arg.CacheType,
		arg.CacheKey,
		arg.PromptHash,
		arg.DataHash,
		arg.Response,
		arg.ExpiresAt,
		arg.ListenCount,
	)
	return err
}

const upsertUserPresence = `-- name: UpsertUserPresence :exec
INSERT INTO user_presence (user_id, last_ping)
VALUES ($1, NOW())
ON CONFLICT (user_id)
DO UPDATE SET last_ping = NOW()
`

func (q *Queries) UpsertUserPresence(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, upsertUserPresence, userID)
	return err
}
