// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_sources.sql

package repository

import (
	"context"
)

const getClientSources = `-- name: GetClientSources :many
SELECT id, user_id, name, token, last_seen, config, created_at FROM client_sources WHERE user_id = $1 ORDER BY last_seen DESC
`

func (q *Queries) GetClientSources(ctx context.Context, userID int32) ([]ClientSource, error) {
	rows, err := q.db.Query(ctx, getClientSources, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientSource
	for rows.Next() {
		var i ClientSource
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Token,
			&i.LastSeen,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClientSource = `-- name: UpsertClientSource :exec
INSERT INTO client_sources (user_id, name, token, last_seen)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, token) DO UPDATE
SET last_seen = NOW(), name = EXCLUDED.name
`

type UpsertClientSourceParams struct {
	UserID int32
	Name   string
	Token  string
}

func (q *Queries) UpsertClientSource(ctx context.Context, arg UpsertClientSourceParams) error {
	_, err := q.db.Exec(ctx, upsertClientSource, arg.UserID, arg.Name, arg.Token)
	return err
}
