// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Role string

const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

// Server-side cache for AI responses with smart refresh
type AiCache struct {
	ID     int32
	UserID int32
	// Type: profile, nowplaying, playlist
	CacheType string
	CacheKey  string
	// MD5 hash of prompt for change detection
	PromptHash string
	// Hash of input data (stats, track info) for change detection
	DataHash    string
	Response    string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   time.Time
	ListenCount pgtype.Int4
}

type AlltimeUserStat struct {
	UserID          int32
	ListenCount     int64
	UniqueTracks    int64
	UniqueAlbums    int64
	UniqueArtists   int64
	SecondsListened interface{}
	FirstListen     interface{}
	LastListen      interface{}
}

type ApiKey struct {
	ID        int32
	Key       string
	UserID    int32
	CreatedAt pgtype.Timestamp
	Label     string
}

type Artist struct {
	ID            int32
	MusicBrainzID *uuid.UUID
	Image         *uuid.UUID
	ImageSource   pgtype.Text
	Genres        []string
	Bio           pgtype.Text
	Popularity    pgtype.Int4
	SpotifyID     pgtype.Text
	Followers     pgtype.Int4
	SearchVector  interface{}
}

type ArtistAlias struct {
	ArtistID  int32
	Alias     string
	Source    string
	IsPrimary bool
}

type ArtistEmbedding struct {
	ArtistID  int32
	Embedding pgvector.Vector
	Model     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ArtistRelease struct {
	ArtistID  int32
	ReleaseID int32
	IsPrimary bool
}

type ArtistTrack struct {
	ArtistID  int32
	TrackID   int32
	IsPrimary bool
}

type ArtistsWithName struct {
	ID            int32
	MusicBrainzID *uuid.UUID
	Image         *uuid.UUID
	ImageSource   pgtype.Text
	Genres        []string
	Bio           pgtype.Text
	Popularity    pgtype.Int4
	SpotifyID     pgtype.Text
	Followers     pgtype.Int4
	Name          string
}

type ClientSource struct {
	ID        uuid.UUID
	UserID    int32
	Name      string
	Token     string
	LastSeen  pgtype.Timestamptz
	Config    []byte
	CreatedAt pgtype.Timestamptz
}

type DailyUserStat struct {
	UserID          int32
	StatDate        pgtype.Date
	ListenCount     int64
	UniqueTracks    int64
	UniqueAlbums    int64
	UniqueArtists   int64
	SecondsListened interface{}
}

type Listen struct {
	TrackID    int32
	ListenedAt time.Time
	Client     *string
	UserID     int32
}

type MonthlyUserStat struct {
	UserID          int32
	StatMonth       pgtype.Date
	ListenCount     int64
	UniqueTracks    int64
	UniqueAlbums    int64
	UniqueArtists   int64
	SecondsListened interface{}
}

type Release struct {
	ID                   int32
	MusicBrainzID        *uuid.UUID
	Image                *uuid.UUID
	VariousArtists       bool
	ImageSource          pgtype.Text
	Genres               []string
	ReleaseDate          pgtype.Text
	Popularity           pgtype.Int4
	SpotifyID            pgtype.Text
	Label                pgtype.Text
	ReleaseDatePrecision pgtype.Text
	SearchVector         interface{}
}

type ReleaseAlias struct {
	ReleaseID int32
	Alias     string
	Source    string
	IsPrimary bool
}

type ReleaseEmbedding struct {
	ReleaseID int32
	Embedding pgvector.Vector
	Model     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ReleasesWithTitle struct {
	ID                   int32
	MusicBrainzID        *uuid.UUID
	Image                *uuid.UUID
	VariousArtists       bool
	ImageSource          pgtype.Text
	Genres               []string
	ReleaseDate          pgtype.Text
	Popularity           pgtype.Int4
	SpotifyID            pgtype.Text
	Label                pgtype.Text
	ReleaseDatePrecision pgtype.Text
	Title                string
}

type Session struct {
	ID         uuid.UUID
	UserID     int32
	CreatedAt  time.Time
	ExpiresAt  time.Time
	Persistent bool
}

type Track struct {
	ID               int32
	MusicBrainzID    *uuid.UUID
	Duration         int32
	ReleaseID        int32
	Popularity       pgtype.Int4
	SpotifyID        pgtype.Text
	Danceability     pgtype.Float8
	Energy           pgtype.Float8
	Key              pgtype.Int4
	Loudness         pgtype.Float8
	Mode             pgtype.Int4
	Speechiness      pgtype.Float8
	Acousticness     pgtype.Float8
	Instrumentalness pgtype.Float8
	Liveness         pgtype.Float8
	Valence          pgtype.Float8
	Tempo            pgtype.Float8
	SearchVector     interface{}
}

type TrackAlias struct {
	TrackID   int32
	Alias     string
	IsPrimary bool
	Source    string
}

type TrackEmbedding struct {
	TrackID   int32
	Embedding pgvector.Vector
	Model     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TracksWithTitle struct {
	ID               int32
	MusicBrainzID    *uuid.UUID
	Duration         int32
	ReleaseID        int32
	Popularity       pgtype.Int4
	SpotifyID        pgtype.Text
	Danceability     pgtype.Float8
	Energy           pgtype.Float8
	Key              pgtype.Int4
	Loudness         pgtype.Float8
	Mode             pgtype.Int4
	Speechiness      pgtype.Float8
	Acousticness     pgtype.Float8
	Instrumentalness pgtype.Float8
	Liveness         pgtype.Float8
	Valence          pgtype.Float8
	Tempo            pgtype.Float8
	Title            string
}

type User struct {
	ID       int32
	Username string
	Role     Role
	Password []byte
}

type UserPreference struct {
	UserID          int32
	PreferencesData []byte
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

// Tracks active user sessions for Now Playing critique optimization
type UserPresence struct {
	UserID   int32
	LastPing time.Time
}

type UserTasteEmbedding struct {
	UserID               int32
	Embedding            pgvector.Vector
	Model                pgtype.Text
	LastComputed         pgtype.Timestamptz
	ListenCountAtCompute pgtype.Int4
}

type UserTheme struct {
	UserID    int32
	ThemeData []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type YearlyUserStat struct {
	UserID          int32
	StatYear        int32
	ListenCount     int64
	UniqueTracks    int64
	UniqueAlbums    int64
	UniqueArtists   int64
	SecondsListened interface{}
}
