// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package repository

import (
	"context"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT preferences_data
FROM user_preferences
WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var preferences_data []byte
	err := row.Scan(&preferences_data)
	return preferences_data, err
}

const saveUserPreferences = `-- name: SaveUserPreferences :exec
INSERT INTO user_preferences (user_id, preferences_data)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET
    preferences_data = EXCLUDED.preferences_data,
    updated_at = now()
`

type SaveUserPreferencesParams struct {
	UserID          int32
	PreferencesData []byte
}

func (q *Queries) SaveUserPreferences(ctx context.Context, arg SaveUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, saveUserPreferences, arg.UserID, arg.PreferencesData)
	return err
}
